/**
 * Pre-configured MCP Server Registry
 *
 * Comprehensive catalog of official & community MCP servers.
 * Each entry is unique â€” no duplicates. OAuth-capable servers include
 * authType + oauth fields. Users provide their own API keys/tokens.
 *
 * Sources:
 * - Official: https://github.com/modelcontextprotocol/servers
 * - GitHub official: https://github.com/github/github-mcp-server
 * - Community: https://github.com/appcypher/awesome-mcp-servers
 */

const MCP_REGISTRY = [
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  VERSION CONTROL
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'github',
    name: 'GitHub',
    description: 'Repos, issues, PRs, actions, code search â€” official GitHub MCP server',
    icon: 'ðŸ™',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    requiredEnv: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
    docsUrl: 'https://github.com/github/github-mcp-server',
    featured: true,
  },
  {
    id: 'github-oauth',
    name: 'GitHub (OAuth)',
    description: 'Full GitHub access via OAuth â€” repos, PRs, issues, CI/CD, code search',
    icon: 'ðŸ™',
    category: 'developer',
    transportType: 'streamable-http',
    authType: 'oauth',
    oauth: {
      authUrl: 'https://github.com/login/oauth/authorize',
      tokenUrl: 'https://github.com/login/oauth/access_token',
      scopes: ['repo', 'read:user', 'read:org'],
    },
    requiredEnv: ['GITHUB_CLIENT_ID', 'GITHUB_CLIENT_SECRET'],
    docsUrl: 'https://github.com/github/github-mcp-server',
    featured: true,
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Interact with GitLab repositories, merge requests, pipelines, and issues',
    icon: 'ðŸ¦Š',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gitlab'],
    requiredEnv: ['GITLAB_PERSONAL_ACCESS_TOKEN'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab',
    featured: false,
  },
  {
    id: 'git',
    name: 'Git',
    description: 'Read and search Git repositories â€” log, diff, blame, branches, tags',
    icon: 'ðŸ“¦',
    category: 'developer',
    transportType: 'stdio',
    command: 'uvx',
    args: ['mcp-server-git'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
    featured: false,
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issues, projects, cycles, triage â€” streamlined project management',
    icon: 'ðŸ“',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-linear'],
    authType: 'oauth',
    oauth: {
      authUrl: 'https://linear.app/oauth/authorize',
      tokenUrl: 'https://api.linear.app/oauth/token',
      scopes: ['read', 'write'],
    },
    requiredEnv: ['LINEAR_API_KEY'],
    docsUrl: 'https://github.com/linear/linear-mcp-server',
    featured: true,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  DATABASES
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Query PostgreSQL databases â€” read-only access with schema inspection',
    icon: 'ðŸ˜',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    requiredEnv: ['POSTGRES_CONNECTION_STRING'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    featured: true,
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Query and analyze SQLite databases with schema introspection',
    icon: 'ðŸ—„ï¸',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    featured: false,
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Query MySQL databases with read-only access and schema exploration',
    icon: 'ðŸ¬',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mysql-mcp-server'],
    requiredEnv: ['MYSQL_HOST', 'MYSQL_USER', 'MYSQL_PASSWORD', 'MYSQL_DATABASE'],
    docsUrl: 'https://github.com/designcomputer/mysql_mcp_server',
    featured: false,
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'Query MongoDB collections, inspect schemas, run aggregation pipelines',
    icon: 'ðŸƒ',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-mongo-server'],
    requiredEnv: ['MONGODB_URI'],
    docsUrl: 'https://github.com/kiliczsh/mcp-mongo-server',
    featured: false,
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'Interact with Redis â€” get, set, delete keys, scan patterns, manage data',
    icon: 'ðŸ”´',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@redis/mcp-server'],
    requiredEnv: ['REDIS_URL'],
    docsUrl: 'https://github.com/redis/mcp-redis',
    featured: false,
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    description: 'Vector database â€” semantic search, embeddings, collections',
    icon: 'ðŸ”·',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@qdrant/mcp-server-qdrant'],
    requiredEnv: ['QDRANT_URL', 'QDRANT_API_KEY'],
    docsUrl: 'https://github.com/qdrant/mcp-server-qdrant',
    featured: false,
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Manage Supabase projects â€” database, auth, storage, edge functions',
    icon: 'âš¡',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-supabase'],
    requiredEnv: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    docsUrl: 'https://github.com/supabase-community/supabase-mcp',
    featured: false,
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Serverless Postgres â€” create databases, run queries, manage branches',
    icon: 'ðŸŒŠ',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@neondatabase/mcp-server-neon'],
    requiredEnv: ['NEON_API_KEY'],
    docsUrl: 'https://github.com/neondatabase/mcp-server-neon',
    featured: false,
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    description: 'Query Google BigQuery datasets and explore schemas',
    icon: 'ðŸ“Š',
    category: 'database',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@mcp/bigquery'],
    requiredEnv: ['GOOGLE_CLOUD_PROJECT'],
    docsUrl: 'https://github.com/LucasHild/mcp-server-bigquery',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  COMMUNICATION
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages, read channels, manage conversations in Slack workspaces',
    icon: 'ðŸ’¬',
    category: 'communication',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    requiredEnv: ['SLACK_BOT_TOKEN', 'SLACK_TEAM_ID'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
    featured: true,
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Read, write, search, and organize emails in Gmail',
    icon: 'ðŸ“§',
    category: 'communication',
    transportType: 'streamable-http',
    authType: 'oauth',
    oauth: {
      authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/gmail.modify'],
    },
    requiredEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    docsUrl: 'https://github.com/googleworkspace/mcp-servers',
    featured: true,
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Search, read, create, and update Notion pages, databases, and blocks',
    icon: 'ðŸ“',
    category: 'communication',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@notionhq/notion-mcp-server'],
    requiredEnv: ['NOTION_API_KEY'],
    docsUrl: 'https://github.com/makenotion/notion-mcp-server',
    featured: true,
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send messages, read channels, manage servers on Discord',
    icon: 'ðŸŽ®',
    category: 'communication',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'discord-mcp'],
    requiredEnv: ['DISCORD_TOKEN'],
    docsUrl: 'https://github.com/v-3/discordmcp',
    featured: false,
  },
  {
    id: 'email',
    name: 'Email (SMTP)',
    description: 'Send emails via SMTP â€” compose, format, attach files',
    icon: 'âœ‰ï¸',
    category: 'communication',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-server-email'],
    requiredEnv: ['SMTP_HOST', 'SMTP_USER', 'SMTP_PASS'],
    docsUrl: 'https://github.com/nicholasrq/mcp-server-email',
    featured: false,
  },
  {
    id: 'microsoft-365',
    name: 'Microsoft 365',
    description: 'Outlook mail, Teams, OneDrive, Calendar via Microsoft Graph',
    icon: 'ðŸ¢',
    category: 'communication',
    transportType: 'streamable-http',
    authType: 'oauth',
    oauth: {
      authUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      scopes: ['Mail.ReadWrite', 'Calendars.ReadWrite', 'Files.ReadWrite'],
    },
    requiredEnv: ['MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET'],
    docsUrl: 'https://github.com/microsoftgraph/microsoft-graph-mcp',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  SEARCH & WEB
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Web and local search using the Brave Search API â€” web pages, news, images',
    icon: 'ðŸ¦',
    category: 'search',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    requiredEnv: ['BRAVE_API_KEY'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    featured: true,
  },
  {
    id: 'fetch',
    name: 'Fetch',
    description: 'Fetch and extract readable content from any web URL, converting HTML to markdown',
    icon: 'ðŸŒ',
    category: 'search',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
    featured: true,
  },
  {
    id: 'exa',
    name: 'Exa',
    description: 'AI-powered web search by Exa â€” semantic search, find similar pages, get contents',
    icon: 'ðŸ”Ž',
    category: 'search',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'exa-mcp-server'],
    requiredEnv: ['EXA_API_KEY'],
    docsUrl: 'https://github.com/exa-labs/exa-mcp-server',
    featured: true,
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    description: 'Web scraping â€” extract structured data from any website',
    icon: 'ðŸ”¥',
    category: 'search',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'firecrawl-mcp'],
    requiredEnv: ['FIRECRAWL_API_KEY'],
    docsUrl: 'https://github.com/mendableai/firecrawl-mcp-server',
    featured: false,
  },
  {
    id: 'tavily',
    name: 'Tavily',
    description: 'AI search engine optimized for LLMs â€” search, extract, and get answers',
    icon: 'ðŸ”',
    category: 'search',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'tavily-mcp'],
    requiredEnv: ['TAVILY_API_KEY'],
    docsUrl: 'https://github.com/tavily-ai/tavily-mcp',
    featured: true,
  },
  {
    id: 'google-maps',
    name: 'Google Maps',
    description: 'Search places, get directions, geocode addresses, find nearby locations',
    icon: 'ðŸ—ºï¸',
    category: 'search',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-google-maps'],
    requiredEnv: ['GOOGLE_MAPS_API_KEY'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  SANDBOX & EXECUTION
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'e2b',
    name: 'E2B',
    description: 'Cloud sandbox â€” run code in isolated environments (Python, JS, etc.)',
    icon: 'ðŸ“¦',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@e2b/mcp-server'],
    requiredEnv: ['E2B_API_KEY'],
    docsUrl: 'https://github.com/e2b-dev/mcp-server',
    featured: false,
  },
  {
    id: 'microsandbox',
    name: 'Microsandbox',
    description: 'Open-source lightweight sandbox for secure code execution',
    icon: 'ðŸ§Š',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'microsandbox-mcp'],
    requiredEnv: [],
    docsUrl: 'https://github.com/microsandbox/microsandbox',
    featured: false,
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Manage Docker containers, images, volumes, and networks',
    icon: 'ðŸ³',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'docker-mcp'],
    requiredEnv: [],
    docsUrl: 'https://github.com/QuantGeekDev/docker-mcp',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  CLOUD & DEVOPS
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'aws',
    name: 'AWS',
    description: 'AWS services â€” S3, Lambda, EC2, DynamoDB, CloudFormation',
    icon: 'ðŸ”¶',
    category: 'cloud',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@awslabs/mcp'],
    requiredEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'],
    docsUrl: 'https://github.com/awslabs/mcp',
    featured: false,
  },
  {
    id: 'aws-kb-retrieval',
    name: 'AWS Knowledge Base',
    description: 'Retrieve and query documents from AWS Bedrock Knowledge Bases using RAG',
    icon: 'â˜ï¸',
    category: 'cloud',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-aws-kb-retrieval'],
    requiredEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/aws-kb-retrieval',
    featured: false,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage Cloudflare Workers, KV, R2, D1, and DNS records',
    icon: 'ðŸŸ ',
    category: 'cloud',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@cloudflare/mcp-server-cloudflare'],
    requiredEnv: ['CLOUDFLARE_API_TOKEN'],
    docsUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    featured: false,
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Manage Vercel deployments, projects, domains, and environment variables',
    icon: 'â–²',
    category: 'cloud',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@vercel/mcp-server'],
    requiredEnv: ['VERCEL_API_TOKEN'],
    docsUrl: 'https://github.com/vercel/vercel-mcp-server',
    featured: false,
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    description: 'Manage pods, deployments, services, and cluster resources',
    icon: 'â˜¸ï¸',
    category: 'cloud',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-k8s'],
    requiredEnv: ['KUBECONFIG'],
    docsUrl: 'https://github.com/strowk/mcp-k8s-go',
    featured: false,
  },
  {
    id: 'terraform',
    name: 'Terraform',
    description: 'Infrastructure as code â€” plan, apply, manage Terraform configs',
    icon: 'ðŸ—ï¸',
    category: 'cloud',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@hashicorp/terraform-mcp-server'],
    requiredEnv: [],
    docsUrl: 'https://github.com/hashicorp/terraform-mcp-server',
    featured: false,
  },
  {
    id: 'pulumi',
    name: 'Pulumi',
    description: 'Infrastructure as code with real programming languages â€” deploy, preview, manage stacks',
    icon: 'ðŸŸ£',
    category: 'cloud',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@pulumi/mcp-server'],
    requiredEnv: ['PULUMI_ACCESS_TOKEN'],
    docsUrl: 'https://github.com/pulumi/mcp-server',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  MONITORING
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking, performance monitoring, issue management â€” official Sentry MCP',
    icon: 'ðŸ›',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@sentry/mcp-server'],
    requiredEnv: ['SENTRY_AUTH_TOKEN', 'SENTRY_ORG'],
    docsUrl: 'https://github.com/getsentry/sentry-mcp',
    featured: false,
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Metrics, traces, logs, alerts, and dashboards from Datadog',
    icon: 'ðŸ•',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@datadog/datadog-mcp-server'],
    requiredEnv: ['DD_API_KEY', 'DD_APP_KEY'],
    docsUrl: 'https://github.com/DataDog/datadog-mcp-server',
    featured: false,
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Query Grafana dashboards, data sources, and alerts',
    icon: 'ðŸ“ˆ',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-grafana'],
    requiredEnv: ['GRAFANA_URL', 'GRAFANA_API_KEY'],
    docsUrl: 'https://github.com/grafana/mcp-grafana',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  PRODUCTIVITY
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'jira',
    name: 'Jira',
    description: 'Manage Jira tickets, sprints, boards, and projects',
    icon: 'ðŸŽ¯',
    category: 'productivity',
    transportType: 'streamable-http',
    authType: 'oauth',
    requiredEnv: ['JIRA_CLIENT_ID', 'JIRA_CLIENT_SECRET'],
    docsUrl: 'https://github.com/atlassian/jira-mcp-server',
    featured: false,
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Tasks, projects, teams, and portfolio management in Asana',
    icon: 'âœ…',
    category: 'productivity',
    transportType: 'streamable-http',
    authType: 'oauth',
    requiredEnv: ['ASANA_CLIENT_ID', 'ASANA_CLIENT_SECRET'],
    docsUrl: 'https://github.com/Asana/asana-mcp-server',
    featured: false,
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'View, create, update, and delete Google Calendar events',
    icon: 'ðŸ“…',
    category: 'productivity',
    transportType: 'streamable-http',
    authType: 'oauth',
    oauth: {
      authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/calendar'],
    },
    requiredEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    docsUrl: 'https://github.com/googleworkspace/mcp-servers',
    featured: true,
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Access and search files in Google Drive, Docs, Sheets, and Slides',
    icon: 'ðŸ“‚',
    category: 'productivity',
    transportType: 'streamable-http',
    authType: 'oauth',
    oauth: {
      authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/drive.readonly'],
    },
    requiredEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive',
    featured: true,
  },
  {
    id: 'todoist',
    name: 'Todoist',
    description: 'Manage Todoist tasks, projects, labels, and filters',
    icon: 'â˜‘ï¸',
    category: 'productivity',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@doist/todoist-mcp'],
    requiredEnv: ['TODOIST_API_TOKEN'],
    docsUrl: 'https://github.com/doist/todoist-mcp',
    featured: false,
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'Manage WordPress posts, pages, media, and site settings via REST API',
    icon: 'ðŸ“°',
    category: 'productivity',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'wordpress-mcp'],
    requiredEnv: ['WORDPRESS_URL', 'WORDPRESS_USERNAME', 'WORDPRESS_APP_PASSWORD'],
    docsUrl: 'https://github.com/mrahmadt/wordpress-mcp',
    featured: false,
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Read, create, update records in Airtable bases and tables',
    icon: 'ðŸ“‹',
    category: 'productivity',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'airtable-mcp'],
    requiredEnv: ['AIRTABLE_API_KEY'],
    docsUrl: 'https://github.com/domdomegg/airtable-mcp-server',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  BROWSER & AUTOMATION
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Browser automation by Microsoft â€” navigate, screenshot, fill forms, click',
    icon: 'ðŸŽ­',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@playwright/mcp@latest'],
    requiredEnv: [],
    docsUrl: 'https://github.com/microsoft/playwright-mcp',
    featured: true,
  },
  {
    id: 'browser-use',
    name: 'Browser-Use',
    description: 'AI-powered browser agent â€” autonomous web navigation and interaction',
    icon: 'ðŸŒ',
    category: 'developer',
    transportType: 'stdio',
    command: 'uvx',
    args: ['browser-use-mcp'],
    requiredEnv: [],
    docsUrl: 'https://github.com/browser-use/browser-use',
    featured: false,
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Browser automation â€” navigate pages, take screenshots, fill forms, click elements',
    icon: 'ðŸª¡',
    category: 'developer',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  MEMORY & KNOWLEDGE
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'memory',
    name: 'Memory',
    description: 'Persistent memory using a local knowledge graph â€” entities, relations, observations',
    icon: 'ðŸ§ ',
    category: 'knowledge',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
    featured: true,
  },
  {
    id: 'graphiti',
    name: 'Graphiti (Zep)',
    description: 'Temporal knowledge graph for persistent memory across sessions',
    icon: 'ðŸ•¸ï¸',
    category: 'knowledge',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'graphiti-mcp'],
    requiredEnv: ['NEO4J_URI', 'NEO4J_USER', 'NEO4J_PASSWORD'],
    docsUrl: 'https://github.com/getzep/graphiti',
    featured: false,
  },
  {
    id: 'context7',
    name: 'Context7',
    description: 'Up-to-date library documentation and code examples for any framework',
    icon: 'ðŸ“–',
    category: 'knowledge',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@upstash/context7-mcp'],
    requiredEnv: [],
    docsUrl: 'https://github.com/upstash/context7',
    featured: true,
  },
  {
    id: 'arxiv',
    name: 'ArXiv',
    description: 'Search and read academic papers from ArXiv â€” abstracts, full text, references',
    icon: 'ðŸ“„',
    category: 'knowledge',
    transportType: 'stdio',
    command: 'uvx',
    args: ['arxiv-mcp-server'],
    requiredEnv: [],
    docsUrl: 'https://github.com/blazickjp/arxiv-mcp-server',
    featured: false,
  },
  {
    id: 'wikipedia',
    name: 'Wikipedia',
    description: 'Search and read Wikipedia articles in any language',
    icon: 'ðŸ“š',
    category: 'knowledge',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'wikipedia-mcp'],
    requiredEnv: [],
    docsUrl: 'https://github.com/wfhendrix11/wikipedia-mcp',
    featured: false,
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Read, search, and manage notes in your Obsidian vault',
    icon: 'ðŸ’Ž',
    category: 'knowledge',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-obsidian'],
    requiredEnv: ['OBSIDIAN_VAULT_PATH'],
    docsUrl: 'https://github.com/smithery-ai/mcp-obsidian',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  FINANCE
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Manage Stripe payments, customers, subscriptions, and invoices',
    icon: 'ðŸ’³',
    category: 'finance',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@stripe/mcp'],
    requiredEnv: ['STRIPE_SECRET_KEY'],
    docsUrl: 'https://github.com/stripe/agent-toolkit',
    featured: true,
  },
  {
    id: 'coinmarket',
    name: 'CoinMarketCap',
    description: 'Cryptocurrency prices, market data, and token information',
    icon: 'â‚¿',
    category: 'finance',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'coinmarket-mcp-server'],
    requiredEnv: ['COINMARKET_API_KEY'],
    docsUrl: 'https://github.com/vidhupv/coinmarket-mcp-server',
    featured: false,
  },
  {
    id: 'alpha-vantage',
    name: 'Alpha Vantage',
    description: 'Stock market data, forex, crypto, and technical indicators',
    icon: 'ðŸ“ˆ',
    category: 'finance',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'alphavantage-mcp'],
    requiredEnv: ['ALPHA_VANTAGE_API_KEY'],
    docsUrl: 'https://github.com/calvernaz/alphavantage',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  SYSTEM & FILES
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read, write, search, and manage files and directories on the local filesystem',
    icon: 'ðŸ“',
    category: 'system',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    featured: true,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  AI & MODELS
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run AI models on Replicate â€” image generation, LLMs, audio, video',
    icon: 'ðŸ¤–',
    category: 'ai',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-replicate'],
    requiredEnv: ['REPLICATE_API_TOKEN'],
    docsUrl: 'https://github.com/deepfates/mcp-replicate',
    featured: false,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Search models, datasets, and spaces on Hugging Face Hub',
    icon: 'ðŸ¤—',
    category: 'ai',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-hfspace'],
    requiredEnv: ['HF_TOKEN'],
    docsUrl: 'https://github.com/evalstate/mcp-hfspace',
    featured: false,
  },
  {
    id: 'everart',
    name: 'EverArt',
    description: 'AI image generation through EverArt â€” create images from text prompts',
    icon: 'ðŸŽ¨',
    category: 'ai',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everart'],
    requiredEnv: ['EVERART_API_KEY'],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everart',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  DESIGN & MEDIA
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'figma',
    name: 'Figma',
    description: 'Extract design data, components, styles, and assets from Figma files',
    icon: 'ðŸŽ¨',
    category: 'design',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'figma-mcp'],
    requiredEnv: ['FIGMA_ACCESS_TOKEN'],
    docsUrl: 'https://github.com/nicholasrq/figma-mcp',
    featured: true,
  },
  {
    id: 'spotify',
    name: 'Spotify',
    description: 'Search music, manage playlists, control playback on Spotify',
    icon: 'ðŸŽµ',
    category: 'media',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'spotify-mcp'],
    requiredEnv: ['SPOTIFY_CLIENT_ID', 'SPOTIFY_CLIENT_SECRET'],
    docsUrl: 'https://github.com/varunneal/spotify-mcp',
    featured: false,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'Search videos, get transcripts, channel info, and video metadata',
    icon: 'â–¶ï¸',
    category: 'media',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'youtube-mcp'],
    requiredEnv: ['YOUTUBE_API_KEY'],
    docsUrl: 'https://github.com/nicholasrq/youtube-mcp',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  SECURITY
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'shodan',
    name: 'Shodan',
    description: 'Search internet-connected devices, check IPs, analyze network exposure',
    icon: 'ðŸ›¡ï¸',
    category: 'security',
    transportType: 'stdio',
    command: 'uvx',
    args: ['mcp-server-shodan'],
    requiredEnv: ['SHODAN_API_KEY'],
    docsUrl: 'https://github.com/BurtTheCoder/mcp-server-shodan',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  REASONING & THINKING
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking',
    description: 'Step-by-step reasoning and dynamic problem solving with revision support',
    icon: 'ðŸ¤”',
    category: 'reasoning',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
    featured: true,
  },
  {
    id: 'everything',
    name: 'Everything',
    description: 'Reference/test server demonstrating all MCP capabilities â€” tools, resources, prompts',
    icon: 'ðŸ§ª',
    category: 'reasoning',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everything'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everything',
    featured: false,
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  //  UTILITIES & AUTOMATION
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'time',
    name: 'Time',
    description: 'Get current time in any timezone and convert between timezones',
    icon: 'â°',
    category: 'utilities',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-time'],
    requiredEnv: [],
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/time',
    featured: false,
  },
  {
    id: 'weather',
    name: 'Weather',
    description: 'Get current weather and forecasts for any location worldwide',
    icon: 'ðŸŒ¤ï¸',
    category: 'utilities',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'weather-mcp'],
    requiredEnv: ['OPENWEATHER_API_KEY'],
    docsUrl: 'https://github.com/magarcia/weather-mcp',
    featured: false,
  },
  {
    id: 'flight-tracker',
    name: 'Flight Tracker',
    description: 'Track flights, get airport info, airline details, and travel data',
    icon: 'âœˆï¸',
    category: 'utilities',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'flight-mcp'],
    requiredEnv: ['AVIATIONSTACK_API_KEY'],
    docsUrl: 'https://github.com/nicholasrq/flight-mcp',
    featured: false,
  },
  {
    id: 'n8n',
    name: 'n8n',
    description: 'Trigger and manage n8n workflows and automations',
    icon: 'âš™ï¸',
    category: 'utilities',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'n8n-mcp'],
    requiredEnv: ['N8N_API_KEY', 'N8N_BASE_URL'],
    docsUrl: 'https://github.com/nicholasrq/n8n-mcp',
    featured: false,
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Trigger Zapier zaps and interact with connected apps',
    icon: 'âš¡',
    category: 'utilities',
    transportType: 'stdio',
    command: 'npx',
    args: ['-y', 'zapier-mcp'],
    requiredEnv: ['ZAPIER_API_KEY'],
    docsUrl: 'https://github.com/nicholasrq/zapier-mcp',
    featured: false,
  },
];

const CATEGORIES = [
  { id: 'featured', name: 'Featured', icon: 'â­', description: 'Most popular integrations' },
  { id: 'developer', name: 'Developer Tools', icon: 'âš¡', description: 'Code, CI/CD, version control, monitoring' },
  { id: 'search', name: 'Search & Web', icon: 'ðŸ”', description: 'Web search, browsing, scraping' },
  { id: 'database', name: 'Databases', icon: 'ðŸ—„ï¸', description: 'SQL, NoSQL, vector, serverless' },
  { id: 'communication', name: 'Communication', icon: 'ðŸ’¬', description: 'Chat, email, messaging' },
  { id: 'cloud', name: 'Cloud & DevOps', icon: 'â˜ï¸', description: 'AWS, GCP, Vercel, Cloudflare, IaC' },
  { id: 'productivity', name: 'Productivity', icon: 'ðŸ“', description: 'Calendar, Drive, project mgmt' },
  { id: 'knowledge', name: 'Knowledge', icon: 'ðŸ“š', description: 'Memory, research, notes, wikis' },
  { id: 'ai', name: 'AI & Models', icon: 'ðŸ¤–', description: 'Model hubs, image generation' },
  { id: 'finance', name: 'Finance', icon: 'ðŸ’³', description: 'Payments, crypto, market data' },
  { id: 'design', name: 'Design', icon: 'ðŸŽ¨', description: 'Figma, assets, UI tools' },
  { id: 'media', name: 'Media', icon: 'ðŸŽµ', description: 'Music, video, streaming' },
  { id: 'security', name: 'Security', icon: 'ðŸ›¡ï¸', description: 'OSINT, monitoring, scanning' },
  { id: 'system', name: 'System', icon: 'ðŸ’»', description: 'Files, OS, shell access' },
  { id: 'reasoning', name: 'Reasoning', icon: 'ðŸ§ ', description: 'Thinking, planning, logic' },
  { id: 'utilities', name: 'Utilities', icon: 'ðŸ”§', description: 'Weather, time, automation' },
];

module.exports = { MCP_REGISTRY, CATEGORIES };
