import {
  Github, GitMerge, GitBranch, Kanban, Database, HardDrive, Leaf, CircleDot,
  Hexagon, Zap, Waves, BarChart3, MessageSquare, Mail, FileText, Gamepad2,
  Send, Building2, Search, Globe, Radar, Flame, ScanSearch, MapPin, Box,
  Container, Ship, Cloud, CloudCog, CloudLightning, Triangle, Network,
  Blocks, Layers, Bug, Activity, LineChart, Target, CheckCircle, Calendar,
  FolderOpen, ListChecks, Newspaper, Table2, Monitor, MousePointer2, Brain,
  Waypoints, BookOpen, FileSearch, Library, Gem, CreditCard, Bitcoin,
  TrendingUp, Folder, Cpu, Smile, Palette, PenTool, Music, PlayCircle,
  Shield, Lightbulb, FlaskConical, Clock, CloudSun, Plane, Settings,
  Star, Code, ClipboardList, Terminal, Wrench, Plug2,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  github: Github,
  'git-merge': GitMerge,
  'git-branch': GitBranch,
  kanban: Kanban,
  database: Database,
  'hard-drive': HardDrive,
  leaf: Leaf,
  'circle-dot': CircleDot,
  hexagon: Hexagon,
  zap: Zap,
  waves: Waves,
  'bar-chart-3': BarChart3,
  'message-square': MessageSquare,
  mail: Mail,
  'file-text': FileText,
  'gamepad-2': Gamepad2,
  send: Send,
  'building-2': Building2,
  search: Search,
  globe: Globe,
  radar: Radar,
  flame: Flame,
  'scan-search': ScanSearch,
  'map-pin': MapPin,
  box: Box,
  container: Container,
  ship: Ship,
  cloud: Cloud,
  'cloud-cog': CloudCog,
  'cloud-lightning': CloudLightning,
  triangle: Triangle,
  network: Network,
  blocks: Blocks,
  layers: Layers,
  bug: Bug,
  activity: Activity,
  'line-chart': LineChart,
  target: Target,
  'check-circle': CheckCircle,
  calendar: Calendar,
  'folder-open': FolderOpen,
  'list-checks': ListChecks,
  newspaper: Newspaper,
  'table-2': Table2,
  monitor: Monitor,
  'mouse-pointer-2': MousePointer2,
  brain: Brain,
  waypoints: Waypoints,
  'book-open': BookOpen,
  'file-search': FileSearch,
  library: Library,
  gem: Gem,
  'credit-card': CreditCard,
  bitcoin: Bitcoin,
  'trending-up': TrendingUp,
  folder: Folder,
  cpu: Cpu,
  smile: Smile,
  palette: Palette,
  'pen-tool': PenTool,
  music: Music,
  'play-circle': PlayCircle,
  shield: Shield,
  lightbulb: Lightbulb,
  'flask-conical': FlaskConical,
  clock: Clock,
  'cloud-sun': CloudSun,
  plane: Plane,
  settings: Settings,
  star: Star,
  code: Code,
  'clipboard-list': ClipboardList,
  terminal: Terminal,
  wrench: Wrench,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Plug2;
}
