/**
 * Static MCP Registry data for client-side rendering.
 * Uses Lucide icon names (no emojis). Monochrome design.
 *
 * Remote URLs from Smithery.ai — the largest MCP server hosting platform.
 * Pattern: https://server.smithery.ai/{qualifiedName}/sse (SSE transport)
 * Servers marked with remoteUrl can connect directly via the API.
 */

export interface RegistryServer {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  transportType: string;
  command?: string;
  args?: string[];
  authType?: string;
  oauth?: { authUrl: string; tokenUrl: string; scopes: string[] };
  requiredEnv: string[];
  docsUrl: string;
  featured: boolean;
  /** Remote MCP server URL (SSE or Streamable HTTP). If set, can connect via API. */
  remoteUrl?: string;
}

export interface RegistryCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
}

export const MCP_SERVERS: RegistryServer[] = [
  // ── FREE / NO AUTH (connect instantly) ──
  { id: 'deepwiki', name: 'DeepWiki', description: 'AI-powered documentation for any GitHub repo — browse structure, read content, ask questions', icon: 'book-open', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://deepwiki.com', featured: true, remoteUrl: 'https://mcp.deepwiki.com/mcp' },

  // ── VERSION CONTROL ──
  { id: 'github', name: 'GitHub', description: 'Repos, issues, PRs, actions, code search — official GitHub MCP server', icon: 'github', category: 'developer', transportType: 'streamable-http', authType: 'oauth', oauth: { authUrl: 'https://github.com/login/oauth/authorize', tokenUrl: 'https://github.com/login/oauth/access_token', scopes: ['repo', 'read:user', 'read:org'] }, requiredEnv: [], docsUrl: 'https://github.com/github/github-mcp-server', featured: true, remoteUrl: 'https://api.githubcopilot.com/mcp/' },
  { id: 'gitlab', name: 'GitLab', description: 'Interact with GitLab repositories, merge requests, pipelines, and issues', icon: 'git-merge', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-gitlab'], authType: 'token', requiredEnv: ['GITLAB_PERSONAL_ACCESS_TOKEN'], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab', featured: false },
  { id: 'git', name: 'Git', description: 'Read and search Git repositories — log, diff, blame, branches, tags', icon: 'git-branch', category: 'developer', transportType: 'stdio', command: 'uvx', args: ['mcp-server-git'], requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git', featured: false },
  { id: 'linear', name: 'Linear', description: 'Issues, projects, cycles, triage — streamlined project management', icon: 'kanban', category: 'developer', transportType: 'streamable-http', authType: 'oauth', oauth: { authUrl: 'https://linear.app/oauth/authorize', tokenUrl: 'https://api.linear.app/oauth/token', scopes: ['read', 'write'] }, requiredEnv: [], docsUrl: 'https://github.com/linear/linear-mcp-server', featured: true, remoteUrl: 'https://mcp.linear.app/sse' },

  // ── DATABASES ──
  { id: 'postgres', name: 'PostgreSQL', description: 'Query PostgreSQL databases via PostgREST — filtering, joins, full CRUD', icon: 'database', category: 'database', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres', featured: true, remoteUrl: 'https://server.smithery.ai/node2flow/postgrest/sse' },
  { id: 'sqlite', name: 'SQLite', description: 'Query and analyze SQLite databases with schema introspection', icon: 'hard-drive', category: 'database', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-sqlite'], requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite', featured: false },
  { id: 'mysql', name: 'MySQL', description: 'Query MySQL databases with read-only access and schema exploration', icon: 'database', category: 'database', transportType: 'stdio', command: 'npx', args: ['-y', 'mysql-mcp-server'], requiredEnv: ['MYSQL_HOST', 'MYSQL_USER', 'MYSQL_PASSWORD', 'MYSQL_DATABASE'], docsUrl: 'https://github.com/designcomputer/mysql_mcp_server', featured: false },
  { id: 'mongodb', name: 'MongoDB', description: 'Query MongoDB collections, inspect schemas, run aggregation pipelines', icon: 'leaf', category: 'database', transportType: 'stdio', command: 'npx', args: ['-y', 'mcp-mongo-server'], requiredEnv: ['MONGODB_URI'], docsUrl: 'https://github.com/kiliczsh/mcp-mongo-server', featured: false },
  { id: 'redis', name: 'Redis', description: 'Interact with Redis — get, set, delete keys, scan patterns, manage data', icon: 'circle-dot', category: 'database', transportType: 'stdio', command: 'npx', args: ['-y', '@redis/mcp-server'], requiredEnv: ['REDIS_URL'], docsUrl: 'https://github.com/redis/mcp-redis', featured: false },
  { id: 'qdrant', name: 'Qdrant', description: 'Vector database — semantic search, embeddings, collections', icon: 'hexagon', category: 'database', transportType: 'stdio', command: 'npx', args: ['-y', '@qdrant/mcp-server-qdrant'], requiredEnv: ['QDRANT_URL', 'QDRANT_API_KEY'], docsUrl: 'https://github.com/qdrant/mcp-server-qdrant', featured: false },
  { id: 'supabase', name: 'Supabase', description: 'Manage Supabase projects — database, auth, storage, edge functions, migrations', icon: 'zap', category: 'database', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/supabase-community/supabase-mcp', featured: true, remoteUrl: 'https://server.smithery.ai/Supabase/sse' },
  { id: 'neon', name: 'Neon', description: 'Serverless Postgres — create databases, run queries, manage branches, schema migrations', icon: 'waves', category: 'database', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/neondatabase/mcp-server-neon', featured: false, remoteUrl: 'https://server.smithery.ai/neon/sse' },
  { id: 'bigquery', name: 'BigQuery', description: 'Run SQL queries on BigQuery datasets, list tables, and inspect schemas', icon: 'bar-chart-3', category: 'database', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/LucasHild/mcp-server-bigquery', featured: false, remoteUrl: 'https://server.smithery.ai/bigquery/sse' },
  { id: 'prisma', name: 'Prisma', description: 'Database toolkit and ORM for TypeScript — query schemas, explore models, manage migrations', icon: 'database', category: 'database', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.prisma.io/', featured: false, remoteUrl: 'https://server.smithery.ai/prisma/sse' },
  { id: 'planetscale', name: 'PlanetScale', description: 'Manage databases, branches, execute SQL, and monitor query performance', icon: 'database', category: 'database', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://planetscale.com/docs/connect/mcp', featured: false, remoteUrl: 'https://server.smithery.ai/planetscale/sse' },

  // ── COMMUNICATION ──
  { id: 'slack', name: 'Slack', description: 'Send messages, read channels, manage conversations — 38 tools for Slack workspace automation', icon: 'message-square', category: 'communication', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack', featured: true, remoteUrl: 'https://server.smithery.ai/node2flow/slack/sse' },
  { id: 'gmail', name: 'Gmail', description: 'Read, write, search, and organize emails — send, draft, reply, forward, manage labels', icon: 'mail', category: 'communication', transportType: 'streamable-http', authType: 'oauth', oauth: { authUrl: 'https://accounts.google.com/o/oauth2/v2/auth', tokenUrl: 'https://oauth2.googleapis.com/token', scopes: ['https://www.googleapis.com/auth/gmail.modify'] }, requiredEnv: [], docsUrl: 'https://github.com/googleworkspace/mcp-servers', featured: true, remoteUrl: 'https://server.smithery.ai/gmail/sse' },
  { id: 'notion', name: 'Notion', description: 'Search, read, create, and update Notion pages, databases, blocks, and comments', icon: 'file-text', category: 'communication', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/makenotion/notion-mcp-server', featured: true, remoteUrl: 'https://server.smithery.ai/notion/sse' },
  { id: 'discord', name: 'Discord', description: 'Manage guilds, channels, roles, members — send messages, reactions, webhooks, events', icon: 'gamepad-2', category: 'communication', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/v-3/discordmcp', featured: false, remoteUrl: 'https://server.smithery.ai/discord/sse' },
  { id: 'email', name: 'Email (SMTP)', description: 'Send emails via SMTP — compose, format, attach files', icon: 'send', category: 'communication', transportType: 'stdio', command: 'npx', args: ['-y', 'mcp-server-email'], requiredEnv: ['SMTP_HOST', 'SMTP_USER', 'SMTP_PASS'], docsUrl: 'https://github.com/nicholasrq/mcp-server-email', featured: false },
  { id: 'microsoft-365', name: 'Microsoft 365', description: 'Outlook mail, Teams, OneDrive, Calendar via Microsoft Graph', icon: 'building-2', category: 'communication', transportType: 'streamable-http', authType: 'oauth', oauth: { authUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token', scopes: ['Mail.ReadWrite', 'Calendars.ReadWrite', 'Files.ReadWrite'] }, requiredEnv: [], docsUrl: 'https://github.com/microsoftgraph/microsoft-graph-mcp', featured: false, remoteUrl: 'https://server.smithery.ai/outlook/sse' },
  { id: 'microsoft-teams', name: 'Microsoft Teams', description: 'Chat, video meetings, file storage, and collaboration within Microsoft 365', icon: 'users', category: 'communication', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.microsoft.com/en-us/microsoft-teams', featured: false, remoteUrl: 'https://server.smithery.ai/microsoft_teams/sse' },
  { id: 'instagram', name: 'Instagram', description: 'Manage Instagram Business and Creator accounts — posts, stories, analytics', icon: 'camera', category: 'communication', transportType: 'streamable-http', authType: 'oauth', requiredEnv: [], docsUrl: 'https://developers.facebook.com/docs/instagram-api/', featured: false, remoteUrl: 'https://server.smithery.ai/instagram/sse' },
  { id: 'reddit', name: 'Reddit', description: 'Browse subreddits, posts, comments — community discussions and viral content', icon: 'message-circle', category: 'communication', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.reddit.com/dev/api/', featured: false, remoteUrl: 'https://server.smithery.ai/reddit/sse' },

  // ── SEARCH & WEB ──
  { id: 'brave-search', name: 'Brave Search', description: 'Web and local search — web pages, news, images with rich structured results', icon: 'search', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/brave/brave-search-mcp-server', featured: true, remoteUrl: 'https://server.smithery.ai/brave/sse' },
  { id: 'fetch', name: 'Fetch', description: 'Fetch and extract readable content from any web URL, converting HTML to markdown', icon: 'globe', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch', featured: true, remoteUrl: 'https://server.smithery.ai/smithery-ai/fetch/sse' },
  { id: 'exa', name: 'Exa', description: 'AI-powered web search — semantic search, find similar pages, code search for agents', icon: 'radar', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/exa-labs/exa-mcp-server', featured: true, remoteUrl: 'https://server.smithery.ai/exa/sse' },
  { id: 'firecrawl', name: 'Firecrawl', description: 'Web scraping — extract structured data from any website', icon: 'flame', category: 'search', transportType: 'stdio', command: 'npx', args: ['-y', 'firecrawl-mcp'], requiredEnv: ['FIRECRAWL_API_KEY'], docsUrl: 'https://github.com/mendableai/firecrawl-mcp-server', featured: false },
  { id: 'tavily', name: 'Tavily', description: 'AI search engine optimized for LLMs — fast, accurate, structured results with sources', icon: 'scan-search', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/tavily-ai/tavily-mcp', featured: true, remoteUrl: 'https://server.smithery.ai/Tavily/sse' },
  { id: 'google-maps', name: 'Google Maps', description: 'Search places, get directions, geocode addresses, find nearby locations', icon: 'map-pin', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps', featured: false, remoteUrl: 'https://server.smithery.ai/google_maps/sse' },
  { id: 'linkup', name: 'Linkup', description: 'Real-time web search with trustworthy, source-backed answers and citations', icon: 'link', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/LinkupPlatform/linkup-mcp-server', featured: false, remoteUrl: 'https://server.smithery.ai/LinkupPlatform/linkup-mcp-server/sse' },
  { id: 'jina', name: 'Jina AI', description: 'AI-powered search and retrieval — search the web, read pages, extract structured data', icon: 'search', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://jina.ai', featured: false, remoteUrl: 'https://server.smithery.ai/jina/sse' },
  { id: 'apify', name: 'Apify', description: 'Web scraping and automation platform — run scrapers, extract structured data', icon: 'bot', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://apify.com', featured: false, remoteUrl: 'https://server.smithery.ai/apify/sse' },
  { id: 'brightdata', name: 'Bright Data', description: 'Web scraping at scale — bypass blocks, crawl, navigate, extract from any site', icon: 'globe', category: 'search', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://brightdata.com', featured: false, remoteUrl: 'https://server.smithery.ai/brightdata/sse' },

  // ── SANDBOX & EXECUTION ──
  { id: 'e2b', name: 'E2B', description: 'Cloud sandbox — run code in isolated environments (Python, JS, etc.)', icon: 'box', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', '@e2b/mcp-server'], requiredEnv: ['E2B_API_KEY'], docsUrl: 'https://github.com/e2b-dev/mcp-server', featured: false },
  { id: 'microsandbox', name: 'Microsandbox', description: 'Open-source lightweight sandbox for secure code execution', icon: 'container', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', 'microsandbox-mcp'], requiredEnv: [], docsUrl: 'https://github.com/microsandbox/microsandbox', featured: false },
  { id: 'docker', name: 'Docker', description: 'Manage Docker containers, images, volumes, and networks', icon: 'ship', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', 'docker-mcp'], requiredEnv: [], docsUrl: 'https://github.com/QuantGeekDev/docker-mcp', featured: false },

  // ── CLOUD & DEVOPS ──
  { id: 'aws', name: 'AWS', description: 'AWS services — S3, Lambda, EC2, DynamoDB, CloudFormation', icon: 'cloud', category: 'cloud', transportType: 'stdio', command: 'npx', args: ['-y', '@awslabs/mcp'], requiredEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'], docsUrl: 'https://github.com/awslabs/mcp', featured: false },
  { id: 'aws-marketplace', name: 'AWS Marketplace', description: 'Browse and manage AWS Marketplace subscriptions and product listings', icon: 'cloud-cog', category: 'cloud', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://aws.amazon.com/marketplace/', featured: false, remoteUrl: 'https://server.smithery.ai/aws-marketplace/sse' },
  { id: 'cloudflare', name: 'Cloudflare', description: 'Manage Workers, R2, KV, D1, DNS — full Cloudflare OpenAPI integration', icon: 'cloud-lightning', category: 'cloud', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/cloudflare/mcp-server-cloudflare', featured: false, remoteUrl: 'https://server.smithery.ai/cloudflare/sse' },
  { id: 'vercel', name: 'Vercel', description: 'Manage deployments, projects, domains, debug builds, search docs', icon: 'triangle', category: 'cloud', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/vercel/vercel-mcp-server', featured: false, remoteUrl: 'https://server.smithery.ai/vercel/sse' },
  { id: 'kubernetes', name: 'Kubernetes', description: 'Manage pods, deployments, services, and cluster resources', icon: 'network', category: 'cloud', transportType: 'stdio', command: 'npx', args: ['-y', 'mcp-k8s'], requiredEnv: ['KUBECONFIG'], docsUrl: 'https://github.com/strowk/mcp-k8s-go', featured: false },
  { id: 'terraform', name: 'Terraform', description: 'Infrastructure as code — plan, apply, manage Terraform configs', icon: 'blocks', category: 'cloud', transportType: 'stdio', command: 'npx', args: ['-y', '@hashicorp/terraform-mcp-server'], requiredEnv: [], docsUrl: 'https://github.com/hashicorp/terraform-mcp-server', featured: false },
  { id: 'pulumi', name: 'Pulumi', description: 'Infrastructure as code with real programming languages — deploy, preview, manage stacks', icon: 'layers', category: 'cloud', transportType: 'stdio', command: 'npx', args: ['-y', '@pulumi/mcp-server'], requiredEnv: ['PULUMI_ACCESS_TOKEN'], docsUrl: 'https://github.com/pulumi/mcp-server', featured: false },

  // ── MONITORING ──
  { id: 'sentry', name: 'Sentry', description: 'Error tracking, performance monitoring, issue management — official Sentry MCP', icon: 'bug', category: 'developer', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/getsentry/sentry-mcp', featured: false, remoteUrl: 'https://server.smithery.ai/sentry/sse' },
  { id: 'datadog', name: 'Datadog', description: 'Metrics, traces, logs, alerts, and dashboards from Datadog', icon: 'activity', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', '@datadog/datadog-mcp-server'], requiredEnv: ['DD_API_KEY', 'DD_APP_KEY'], docsUrl: 'https://github.com/DataDog/datadog-mcp-server', featured: false },
  { id: 'grafana', name: 'Grafana', description: 'Query Grafana dashboards, data sources, and alerts', icon: 'line-chart', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', 'mcp-grafana'], requiredEnv: ['GRAFANA_URL', 'GRAFANA_API_KEY'], docsUrl: 'https://github.com/grafana/mcp-grafana', featured: false },

  // ── PRODUCTIVITY ──
  { id: 'jira', name: 'Jira', description: 'Manage Jira tickets, sprints, boards, and projects', icon: 'target', category: 'productivity', transportType: 'streamable-http', authType: 'oauth', requiredEnv: [], docsUrl: 'https://github.com/atlassian/jira-mcp-server', featured: false },
  { id: 'asana', name: 'Asana', description: 'Tasks, projects, teams, and portfolio management in Asana', icon: 'check-circle', category: 'productivity', transportType: 'streamable-http', authType: 'oauth', requiredEnv: [], docsUrl: 'https://github.com/Asana/asana-mcp-server', featured: false, remoteUrl: 'https://server.smithery.ai/asana/sse' },
  { id: 'google-calendar', name: 'Google Calendar', description: 'Schedule events, check availability, manage calendars, set reminders', icon: 'calendar', category: 'productivity', transportType: 'streamable-http', authType: 'oauth', oauth: { authUrl: 'https://accounts.google.com/o/oauth2/v2/auth', tokenUrl: 'https://oauth2.googleapis.com/token', scopes: ['https://www.googleapis.com/auth/calendar'] }, requiredEnv: [], docsUrl: 'https://github.com/googleworkspace/mcp-servers', featured: true, remoteUrl: 'https://server.smithery.ai/googlecalendar/sse' },
  { id: 'google-drive', name: 'Google Drive', description: 'Upload, organize, share files — manage folders, permissions, and search documents', icon: 'folder-open', category: 'productivity', transportType: 'streamable-http', authType: 'oauth', oauth: { authUrl: 'https://accounts.google.com/o/oauth2/v2/auth', tokenUrl: 'https://oauth2.googleapis.com/token', scopes: ['https://www.googleapis.com/auth/drive.readonly'] }, requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive', featured: true, remoteUrl: 'https://server.smithery.ai/googledrive/sse' },
  { id: 'google-docs', name: 'Google Docs', description: 'Cloud-based word processor — real-time collaboration, version history, comments', icon: 'file-text', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://docs.google.com', featured: false, remoteUrl: 'https://server.smithery.ai/googledocs/sse' },
  { id: 'google-sheets', name: 'Google Sheets', description: 'Read, write, format spreadsheets — manage sheets, run formulas, collaborate', icon: 'table-2', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://sheets.google.com', featured: false, remoteUrl: 'https://server.smithery.ai/googlesheets/sse' },
  { id: 'google-slides', name: 'Google Slides', description: 'Create and edit presentations — real-time collaboration, templates, formatting', icon: 'presentation', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://slides.google.com', featured: false, remoteUrl: 'https://server.smithery.ai/googleslides/sse' },
  { id: 'google-tasks', name: 'Google Tasks', description: 'Simple task management integrated with Gmail and Google Calendar', icon: 'list-checks', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://support.google.com/tasks', featured: false, remoteUrl: 'https://server.smithery.ai/googletasks/sse' },
  { id: 'todoist', name: 'Todoist', description: 'Manage tasks, projects, labels, deadlines, and collaborate with team', icon: 'list-checks', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/doist/todoist-mcp', featured: false, remoteUrl: 'https://server.smithery.ai/todoist/sse' },
  { id: 'wordpress', name: 'WordPress', description: 'Manage WordPress posts, pages, media, and site settings via REST API', icon: 'newspaper', category: 'productivity', transportType: 'stdio', command: 'npx', args: ['-y', 'wordpress-mcp'], requiredEnv: ['WORDPRESS_URL', 'WORDPRESS_USERNAME', 'WORDPRESS_APP_PASSWORD'], docsUrl: 'https://github.com/mrahmadt/wordpress-mcp', featured: false },
  { id: 'airtable', name: 'Airtable', description: 'Build databases with spreadsheet simplicity — records, tables, views, automations', icon: 'table-2', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/domdomegg/airtable-mcp-server', featured: false, remoteUrl: 'https://server.smithery.ai/airtable/sse' },
  { id: 'confluence', name: 'Confluence', description: 'Team collaboration and knowledge management — pages, spaces, comments', icon: 'book', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.atlassian.com/software/confluence', featured: false, remoteUrl: 'https://server.smithery.ai/confluence/sse' },
  { id: 'canva', name: 'Canva', description: 'Design suite — create social media graphics, presentations, and marketing materials', icon: 'palette', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.canva.com', featured: false, remoteUrl: 'https://server.smithery.ai/canva/sse' },
  { id: 'bitbucket', name: 'Bitbucket', description: 'Git repos with built-in CI/CD — pull requests, branches, builds', icon: 'git-branch', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://bitbucket.org', featured: false, remoteUrl: 'https://server.smithery.ai/bitbucket/sse' },

  // ── BROWSER & AUTOMATION ──
  { id: 'playwright', name: 'Playwright', description: 'Browser automation by Microsoft — navigate, screenshot, fill forms, click', icon: 'monitor', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', '@playwright/mcp@latest'], requiredEnv: [], docsUrl: 'https://github.com/microsoft/playwright-mcp', featured: true },
  { id: 'browser-use', name: 'Browser-Use', description: 'AI-powered browser agent — autonomous web navigation and interaction', icon: 'globe', category: 'developer', transportType: 'stdio', command: 'uvx', args: ['browser-use-mcp'], requiredEnv: [], docsUrl: 'https://github.com/browser-use/browser-use', featured: false },
  { id: 'puppeteer', name: 'Puppeteer', description: 'Browser automation — navigate pages, take screenshots, fill forms, click elements', icon: 'mouse-pointer-2', category: 'developer', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-puppeteer'], requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer', featured: false },
  { id: 'tldraw', name: 'tldraw', description: 'Create and edit diagrams, wireframes, and sketches — export and collaborate visually', icon: 'pen-tool', category: 'developer', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://tldraw.com', featured: false, remoteUrl: 'https://server.smithery.ai/tldraw/sse' },

  // ── MEMORY & KNOWLEDGE ──
  { id: 'memory', name: 'Memory (Mem0)', description: 'Save, search, and manage long-term memories — facts, preferences, conversations', icon: 'brain', category: 'knowledge', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/mem0ai/mem0', featured: true, remoteUrl: 'https://server.smithery.ai/mem0ai/mem0-memory-mcp/sse' },
  { id: 'graphiti', name: 'Graphiti (Zep)', description: 'Temporal knowledge graph for persistent memory across sessions', icon: 'waypoints', category: 'knowledge', transportType: 'stdio', command: 'npx', args: ['-y', 'graphiti-mcp'], requiredEnv: ['NEO4J_URI', 'NEO4J_USER', 'NEO4J_PASSWORD'], docsUrl: 'https://github.com/getzep/graphiti', featured: false },
  { id: 'context7', name: 'Context7', description: 'Up-to-date library documentation and code examples for any framework', icon: 'book-open', category: 'knowledge', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/upstash/context7', featured: true, remoteUrl: 'https://server.smithery.ai/upstash/context7-mcp/sse' },
  { id: 'arxiv', name: 'ArXiv', description: 'Search and read academic papers from ArXiv — abstracts, full text, references', icon: 'file-search', category: 'knowledge', transportType: 'stdio', command: 'uvx', args: ['arxiv-mcp-server'], requiredEnv: [], docsUrl: 'https://github.com/blazickjp/arxiv-mcp-server', featured: false },
  { id: 'wikipedia', name: 'Wikipedia', description: 'Search and read Wikipedia articles in any language', icon: 'library', category: 'knowledge', transportType: 'stdio', command: 'npx', args: ['-y', 'wikipedia-mcp'], requiredEnv: [], docsUrl: 'https://github.com/wfhendrix11/wikipedia-mcp', featured: false },
  { id: 'obsidian', name: 'Obsidian', description: 'Read, search, and manage notes in your Obsidian vault', icon: 'gem', category: 'knowledge', transportType: 'stdio', command: 'npx', args: ['-y', 'mcp-obsidian'], requiredEnv: ['OBSIDIAN_VAULT_PATH'], docsUrl: 'https://github.com/smithery-ai/mcp-obsidian', featured: false },
  { id: 'deepwiki', name: 'DeepWiki', description: 'Explore GitHub repository documentation by topic — ask questions, get concise answers', icon: 'book-open', category: 'knowledge', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://deepwiki.com', featured: false, remoteUrl: 'https://server.smithery.ai/deepwiki/sse' },
  { id: 'docfork', name: 'Docfork', description: 'Search and retrieve documentation from GitHub repos and the web for technical answers', icon: 'file-search', category: 'knowledge', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://docfork.com', featured: false, remoteUrl: 'https://server.smithery.ai/docfork/docfork/sse' },
  { id: 'microsoft-learn', name: 'Microsoft Learn', description: 'Search Microsoft official documentation — up-to-date guidance for all MS products', icon: 'book', category: 'knowledge', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/microsoftdocs/mcp', featured: false, remoteUrl: 'https://server.smithery.ai/microsoft/learn_mcp/sse' },

  // ── FINANCE ──
  { id: 'stripe', name: 'Stripe', description: 'Manage payments, customers, subscriptions, invoices, disputes, and refunds', icon: 'credit-card', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/stripe/agent-toolkit', featured: true, remoteUrl: 'https://server.smithery.ai/stripe/sse' },
  { id: 'coinmarket', name: 'CoinMarketCap', description: 'Cryptocurrency prices, market data, and token information', icon: 'bitcoin', category: 'finance', transportType: 'stdio', command: 'npx', args: ['-y', 'coinmarket-mcp-server'], requiredEnv: ['COINMARKET_API_KEY'], docsUrl: 'https://github.com/vidhupv/coinmarket-mcp-server', featured: false },
  { id: 'alpha-vantage', name: 'Alpha Vantage', description: 'Stock market data, forex, crypto, and technical indicators', icon: 'trending-up', category: 'finance', transportType: 'stdio', command: 'npx', args: ['-y', 'alphavantage-mcp'], requiredEnv: ['ALPHA_VANTAGE_API_KEY'], docsUrl: 'https://github.com/calvernaz/alphavantage', featured: false },

  // ── SYSTEM & FILES ──
  { id: 'filesystem', name: 'Filesystem', description: 'Read, write, search, and manage files and directories on the local filesystem', icon: 'folder', category: 'system', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem'], requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem', featured: true },

  // ── AI & MODELS ──
  { id: 'replicate', name: 'Replicate', description: 'Run AI models on Replicate — image generation, LLMs, audio, video', icon: 'cpu', category: 'ai', transportType: 'stdio', command: 'npx', args: ['-y', 'mcp-replicate'], requiredEnv: ['REPLICATE_API_TOKEN'], docsUrl: 'https://github.com/deepfates/mcp-replicate', featured: false },
  { id: 'huggingface', name: 'Hugging Face', description: 'AI model hub — discover models, explore datasets, access documentation', icon: 'smile', category: 'ai', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://huggingface.co', featured: false, remoteUrl: 'https://server.smithery.ai/huggingface/sse' },
  { id: 'everart', name: 'EverArt', description: 'AI image generation through EverArt — create images from text prompts', icon: 'palette', category: 'ai', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-everart'], requiredEnv: ['EVERART_API_KEY'], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everart', featured: false },
  { id: 'gemini', name: 'Gemini', description: 'Google Gemini — Veo 3 video generation, Flash text, chat completions, multimodal AI', icon: 'sparkles', category: 'ai', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://ai.google.dev/', featured: false, remoteUrl: 'https://server.smithery.ai/gemini/sse' },

  // ── DESIGN & MEDIA ──
  { id: 'figma', name: 'Figma', description: 'Extract design data, components, styles, and assets from Figma files', icon: 'pen-tool', category: 'design', transportType: 'stdio', command: 'npx', args: ['-y', 'figma-mcp'], requiredEnv: ['FIGMA_ACCESS_TOKEN'], docsUrl: 'https://github.com/nicholasrq/figma-mcp', featured: true },
  { id: 'spotify', name: 'Spotify', description: 'Browse music, manage playlists, control playback, explore listening history', icon: 'music', category: 'media', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/varunneal/spotify-mcp', featured: false, remoteUrl: 'https://server.smithery.ai/arjunkmrm/spotify/sse' },
  { id: 'youtube', name: 'YouTube', description: 'Search videos, get transcripts, channel info — user-generated content, live streaming', icon: 'play-circle', category: 'media', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/nicholasrq/youtube-mcp', featured: false, remoteUrl: 'https://server.smithery.ai/youtube/sse' },

  // ── SECURITY ──
  { id: 'shodan', name: 'Shodan', description: 'Search internet-connected devices, check IPs, analyze network exposure', icon: 'shield', category: 'security', transportType: 'stdio', command: 'uvx', args: ['mcp-server-shodan'], requiredEnv: ['SHODAN_API_KEY'], docsUrl: 'https://github.com/BurtTheCoder/mcp-server-shodan', featured: false },

  // ── REASONING ──
  { id: 'sequential-thinking', name: 'Sequential Thinking', description: 'Step-by-step reasoning and dynamic problem solving with revision support', icon: 'lightbulb', category: 'reasoning', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'], requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking', featured: true },
  { id: 'everything', name: 'Everything', description: 'Reference/test server demonstrating all MCP capabilities — tools, resources, prompts', icon: 'flask-conical', category: 'reasoning', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-everything'], requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everything', featured: false },

  // ── UTILITIES ──
  { id: 'time', name: 'Time', description: 'Get current time in any timezone and convert between timezones', icon: 'clock', category: 'utilities', transportType: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-time'], requiredEnv: [], docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/time', featured: false },
  { id: 'weather', name: 'Weather', description: 'Get current weather and forecasts for any location worldwide', icon: 'cloud-sun', category: 'utilities', transportType: 'stdio', command: 'npx', args: ['-y', 'weather-mcp'], requiredEnv: ['OPENWEATHER_API_KEY'], docsUrl: 'https://github.com/magarcia/weather-mcp', featured: false },
  { id: 'flight-tracker', name: 'Flight Tracker', description: 'Track flights, get airport info, airline details, and travel data', icon: 'plane', category: 'utilities', transportType: 'stdio', command: 'npx', args: ['-y', 'flight-mcp'], requiredEnv: ['AVIATIONSTACK_API_KEY'], docsUrl: 'https://github.com/nicholasrq/flight-mcp', featured: false },
  { id: 'n8n', name: 'n8n', description: 'Manage n8n workflows, executions, credentials, tags, and users', icon: 'settings', category: 'utilities', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/nicholasrq/n8n-mcp', featured: false, remoteUrl: 'https://server.smithery.ai/node2flow/n8n-management/sse' },
  { id: 'zapier', name: 'Zapier', description: 'Connect and automate workflows across 7,000+ services — create and trigger zaps', icon: 'zap', category: 'utilities', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/nicholasrq/zapier-mcp', featured: false, remoteUrl: 'https://server.smithery.ai/zapier/sse' },

  // ── CRM & SALES (les trucs chiants que personne veut faire) ──
  { id: 'hubspot', name: 'HubSpot', description: 'CRM complet — contacts, deals, pipelines, tickets, marketing automation, email sequences', icon: 'target', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://hubspot.com', featured: true, remoteUrl: 'https://server.smithery.ai/hubspot/sse' },
  { id: 'salesforce', name: 'Salesforce', description: 'CRM leader mondial — leads, opportunities, accounts, reports, forecasts, dashboards', icon: 'cloud', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://salesforce.com', featured: true, remoteUrl: 'https://server.smithery.ai/salesforce/sse' },
  { id: 'pipedrive', name: 'Pipedrive', description: 'Pipeline de vente visuel — deals, contacts, activités, emails, prévisions de revenus', icon: 'bar-chart-3', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://pipedrive.com', featured: false, remoteUrl: 'https://server.smithery.ai/pipedrive/sse' },
  { id: 'close-crm', name: 'Close', description: 'CRM pour closers — appels, emails, SMS, pipeline, lead scoring, sequences automatisées', icon: 'phone', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://close.com', featured: false, remoteUrl: 'https://server.smithery.ai/close/sse' },
  { id: 'attio', name: 'Attio', description: 'CRM nouvelle génération — relations, workflows custom, enrichissement automatique de contacts', icon: 'users', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://attio.com', featured: false, remoteUrl: 'https://server.smithery.ai/attio/sse' },
  { id: 'zoho-crm', name: 'Zoho CRM', description: 'CRM + email marketing + facturation — contacts, deals, campagnes, workflows, rapports', icon: 'briefcase', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://zoho.com', featured: false, remoteUrl: 'https://server.smithery.ai/zoho/sse' },
  { id: 'dynamics365', name: 'Dynamics 365', description: 'ERP + CRM Microsoft — ventes, service, finance, opérations, leads, commandes, rapports', icon: 'building-2', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://dynamics.microsoft.com', featured: false, remoteUrl: 'https://server.smithery.ai/dynamics365/sse' },

  // ── PROSPECTION & LEAD GEN (la corvée ultime) ──
  { id: 'prospector', name: 'Prospector', description: 'Trouver des emails de prospects — recherche de contacts, validation d\'adresses, listes de leads', icon: 'crosshair', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://smithery.ai/servers/MyceliumLabs/prospector-mcp-email-finder', featured: true, remoteUrl: 'https://server.smithery.ai/MyceliumLabs/prospector-mcp-email-finder/sse' },
  { id: 'lead-gen', name: 'Lead Gen (FlipFactory)', description: 'Génération de leads gratuite — recherche business, enrichissement, trouveur d\'emails, export CSV', icon: 'user-plus', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/FlipFactory-it-com/flipfactory-mcp-leadgen', featured: true, remoteUrl: 'https://server.smithery.ai/flipfactory/mcp-leadgen/sse' },
  { id: 'sales-intelligence', name: 'Sales Intelligence', description: '12-en-1 — recherche entreprises, enrichissement leads, scoring, CRM sync, email outreach, analytics pipeline', icon: 'search', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://mcp.ariaagent.agency', featured: true, remoteUrl: 'https://server.smithery.ai/aria-agentworks/sales-intelligencee/sse' },
  { id: 'datamerge', name: 'DataMerge', description: 'Enrichissement de données — profils LinkedIn, hiérarchies d\'entreprises, recherche de lookalikes', icon: 'database', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.datamerge.ai', featured: false, remoteUrl: 'https://server.smithery.ai/datamerge/enrich/sse' },
  { id: 'cold-email', name: 'MachFive Cold Email', description: 'Séquences d\'emails à froid hyper-personnalisés — campagnes, génération par lot, export CSV/JSON', icon: 'mail', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://help.machfive.io/categories/integrations/machfive-mcp-server', featured: false, remoteUrl: 'https://server.smithery.ai/machfive/cold-email/sse' },
  { id: 'common-room', name: 'Common Room', description: 'Signaux communautaires — activité cross-canal, contributeurs clés, leads qualifiés produit', icon: 'users', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://commonroom.io', featured: false, remoteUrl: 'https://server.smithery.ai/commonroom/sse' },
  { id: 'google-maps-leads', name: 'Google Maps Leads', description: 'Scraper Google Maps — listes de prospects B2B, validation emails, infos business locaux', icon: 'map-pin', category: 'sales', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://apify.com/nexgendata', featured: false, remoteUrl: 'https://server.smithery.ai/nexgendata-apify/google-maps-mcp-server/sse' },

  // ── EMAIL MARKETING (les relances, newsletters, séquences...) ──
  { id: 'mailchimp', name: 'Mailchimp', description: 'Email marketing — campagnes, audiences, segmentation, templates, analytics d\'engagement', icon: 'mail', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://mailchimp.com', featured: true, remoteUrl: 'https://server.smithery.ai/mailchimp/sse' },
  { id: 'klaviyo', name: 'Klaviyo', description: 'Email + SMS marketing e-commerce — segments, flows automatisés, taux d\'ouverture, analytics', icon: 'mail', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://klaviyo.com', featured: false, remoteUrl: 'https://server.smithery.ai/klaviyo/sse' },
  { id: 'mailerlite', name: 'MailerLite', description: 'Email marketing et automation — campagnes, abonnés, workflows automatisés, landing pages', icon: 'send', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://mailerlite.com', featured: false, remoteUrl: 'https://server.smithery.ai/mailerlite/sse' },

  // ── RÉSEAUX SOCIAUX (poster, planifier, analyser — la galère quotidienne) ──
  { id: 'linkedin', name: 'LinkedIn', description: 'Profil pro, posts, connexions, pages entreprise — engagement, networking, recrutement', icon: 'briefcase', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://linkedin.com', featured: true, remoteUrl: 'https://server.smithery.ai/linkedin/sse' },
  { id: 'twitter', name: 'X (Twitter)', description: 'Tweets, threads, médias, timeline, mentions, likes, retweets — gestion communauté', icon: 'message-circle', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://x.com', featured: true, remoteUrl: 'https://server.smithery.ai/twitter/sse' },
  { id: 'postpulse', name: 'PostPulse', description: 'Publication multi-plateforme — Instagram, Facebook, LinkedIn, X, TikTok, YouTube, Discord', icon: 'share-2', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://developers.post-pulse.com', featured: false, remoteUrl: 'https://server.smithery.ai/post-pulse/mcp-server/sse' },
  { id: 'vibe-marketing', name: 'Vibe Marketing', description: 'Création de contenu IA pour tous les réseaux — templates, frameworks, posts engageants', icon: 'sparkles', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://hyperfeed.ai', featured: false, remoteUrl: 'https://server.smithery.ai/synthetic-ci/vibe-marketing/sse' },
  { id: 'supermetrics', name: 'Supermetrics', description: 'Données marketing de 150+ plateformes — rapports cross-canal, dépenses pub, ROI campagnes', icon: 'bar-chart-3', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://supermetrics.com', featured: false, remoteUrl: 'https://server.smithery.ai/supermetrics/sse' },

  // ── SEO & ADS (les audits interminables) ──
  { id: 'google-search-console', name: 'Google Search Console', description: 'Monitoring SEO — positions, clics, impressions, couverture d\'index, erreurs de crawl', icon: 'search', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://search.google.com/search-console', featured: true, remoteUrl: 'https://server.smithery.ai/google_search_console/sse' },
  { id: 'google-ads', name: 'Google Ads', description: 'Campagnes publicitaires Google — enchères, audiences, budgets, conversions, rapports de performance', icon: 'megaphone', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://ads.google.com', featured: false, remoteUrl: 'https://server.smithery.ai/googleads/sse' },
  { id: 'ahrefs', name: 'Ahrefs', description: 'SEO avancé — backlinks, keywords, ranking, audit technique, analyse concurrence, trafic organique', icon: 'link', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://ahrefs.com', featured: false, remoteUrl: 'https://server.smithery.ai/ahrefs/sse' },
  { id: 'meta-ads', name: 'Meta Ads', description: 'Facebook/Instagram Ads — campagnes, audiences, ROAS, CPA, audit de compte, optimisation budget', icon: 'megaphone', category: 'marketing', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.adadvisor.ai', featured: false, remoteUrl: 'https://server.smithery.ai/adadvisor/meta-ads/sse' },

  // ── COMPTABILITÉ & FACTURATION (la paperasse administrative) ──
  { id: 'quickbooks', name: 'QuickBooks', description: 'Compta cloud — factures, dépenses, rapprochement bancaire, rapports financiers, TVA', icon: 'calculator', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://quickbooks.intuit.com', featured: true, remoteUrl: 'https://server.smithery.ai/quickbooks/sse' },
  { id: 'xero', name: 'Xero', description: 'Comptabilité cloud — facturation, rapprochement bancaire, notes de frais, reporting temps réel', icon: 'calculator', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://xero.com', featured: false, remoteUrl: 'https://server.smithery.ai/xero/sse' },
  { id: 'freshbooks', name: 'FreshBooks', description: 'Facturation et comptabilité PME — devis, factures, suivi du temps, notes de frais', icon: 'file-text', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://freshbooks.com', featured: false, remoteUrl: 'https://server.smithery.ai/freshbooks/sse' },
  { id: 'zoho-books', name: 'Zoho Books', description: 'Comptabilité, facturation, suivi des dépenses — collaboration temps réel, intégration Zoho', icon: 'book', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://zoho.com/books', featured: false, remoteUrl: 'https://server.smithery.ai/zoho_books/sse' },
  { id: 'harvest', name: 'Harvest', description: 'Suivi du temps facturable — projets, factures, notes de frais, capacité équipe, rapports', icon: 'clock', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://getharvest.com', featured: false, remoteUrl: 'https://server.smithery.ai/harvest/sse' },
  { id: 'paypal', name: 'PayPal', description: 'Paiements en ligne — liens de paiement, factures, transactions, suivi des virements', icon: 'credit-card', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://paypal.com', featured: false, remoteUrl: 'https://server.smithery.ai/paypal/sse' },
  { id: 'square', name: 'Square', description: 'Paiements, abonnements, factures, litiges — TPE, encaissements cartes, suivi des ventes', icon: 'credit-card', category: 'finance', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://squareup.com', featured: false, remoteUrl: 'https://server.smithery.ai/square/sse' },

  // ── SUPPORT CLIENT (répondre aux tickets, SLA, base de connaissances) ──
  { id: 'zendesk', name: 'Zendesk', description: 'Tickets support, articles help center, conversations client — SLA, agents, base de connaissances', icon: 'headphones', category: 'support', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://zendesk.com', featured: true, remoteUrl: 'https://server.smithery.ai/zendesk/sse' },
  { id: 'intercom', name: 'Intercom', description: 'Chat live, tickets support, messages ciblés — données utilisateur, réponses automatisées', icon: 'message-square', category: 'support', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://intercom.com', featured: true, remoteUrl: 'https://server.smithery.ai/intercom/sse' },
  { id: 'gorgias', name: 'Gorgias', description: 'Helpdesk e-commerce — support automatisé, gestion commandes, communication client unifiée', icon: 'headphones', category: 'support', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://gorgias.com', featured: false, remoteUrl: 'https://server.smithery.ai/gorgias/sse' },

  // ── E-COMMERCE (commandes, stock, produits, clients) ──
  { id: 'shopify', name: 'Shopify', description: 'Boutique en ligne — produits, commandes, stock, clients, fulfillment, rapports de vente', icon: 'shopping-bag', category: 'ecommerce', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://shopify.com', featured: true, remoteUrl: 'https://server.smithery.ai/shopify/sse' },
  { id: 'wix', name: 'Wix', description: 'Site web drag-and-drop — pages, contenu, domaines, publication, e-commerce intégré', icon: 'layout', category: 'ecommerce', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://wix.com', featured: false, remoteUrl: 'https://server.smithery.ai/wix/sse' },

  // ── RH & RECRUTEMENT (screening CV, paie, onboarding) ──
  { id: 'gusto', name: 'Gusto', description: 'Paie, avantages sociaux, conformité RH — onboarding, congés, déclarations fiscales', icon: 'users', category: 'hr', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://gusto.com', featured: false, remoteUrl: 'https://server.smithery.ai/gusto/sse' },
  { id: 'jobgpt', name: 'JobGPT AutoApply', description: 'Recherche d\'emploi automatisée — candidatures auto, CV sur mesure, outreach recruteurs, 34 outils', icon: 'briefcase', category: 'hr', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://github.com/6figr-com/jobgpt-mcp-server', featured: true, remoteUrl: 'https://server.smithery.ai/xfigr-com/jobgpt/sse' },

  // ── PLANNING & SCHEDULING (la danse des calendriers) ──
  { id: 'calendly', name: 'Calendly', description: 'Planification de RDV — types d\'événements, disponibilité, réservation, liens de scheduling', icon: 'calendar', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://calendly.com', featured: true, remoteUrl: 'https://server.smithery.ai/calendly/sse' },

  // ── STOCKAGE & FICHIERS (organisation, partage, permissions) ──
  { id: 'dropbox', name: 'Dropbox', description: 'Stockage cloud — sync fichiers, dossiers partagés, permissions, collaboration documents', icon: 'folder', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://dropbox.com', featured: false, remoteUrl: 'https://server.smithery.ai/dropbox/sse' },

  // ── FORMULAIRES & ENQUÊTES (création, collecte, analyse) ──
  { id: 'jotform', name: 'Jotform', description: 'Formulaires et enquêtes en ligne — créer, gérer, collecter réponses, workflows automatisés', icon: 'clipboard-list', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://jotform.com', featured: false, remoteUrl: 'https://server.smithery.ai/jotform/sse' },
  { id: 'surveymonkey', name: 'SurveyMonkey', description: 'Création et analyse de sondages — distribution, segmentation, rapports statistiques', icon: 'clipboard-list', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://surveymonkey.com', featured: false, remoteUrl: 'https://server.smithery.ai/survey_monkey/sse' },
  { id: 'typeform', name: 'Typeform / Weavely', description: 'Formulaires conversationnels — 25+ types d\'éléments, logique conditionnelle, thèmes, multi-pages', icon: 'text-cursor-input', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://www.weavely.ai', featured: false, remoteUrl: 'https://server.smithery.ai/florian/weavely/sse' },

  // ── GESTION DE PROJET (suivi tâches, sprints, deadlines) ──
  { id: 'monday', name: 'Monday.com', description: 'Gestion de projet customisable — planification, collaboration, agile, ventes, marketing, automation', icon: 'kanban', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://monday.com', featured: false, remoteUrl: 'https://server.smithery.ai/monday/sse' },
  { id: 'clickup', name: 'ClickUp', description: 'Workspace tout-en-un — tâches, docs, timers, tags, commentaires rich text, hiérarchies complexes', icon: 'check-square', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://clickup.com', featured: false, remoteUrl: 'https://server.smithery.ai/taazkareem/clickup-mcp-premium/sse' },

  // ── WHATSAPP (messages clients, notifications, campagnes) ──
  { id: 'whatsapp', name: 'WhatsApp Business', description: 'API WhatsApp Business — messages, templates, chatbots, campagnes, CRM intégré', icon: 'message-circle', category: 'communication', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://manycontacts.com', featured: false, remoteUrl: 'https://server.smithery.ai/manycontacts/whatsapp-mcp/sse' },

  // ── GOOGLE SUPER (tout Google en un seul connecteur) ──
  { id: 'google-super', name: 'Google Super', description: 'Tous les services Google — Drive, Calendar, Gmail, Sheets, Analytics, Ads — plateforme unifiée', icon: 'layers', category: 'productivity', transportType: 'streamable-http', requiredEnv: [], docsUrl: 'https://google.com', featured: true, remoteUrl: 'https://server.smithery.ai/googlesuper/sse' },
];

export const MCP_CATEGORIES: RegistryCategory[] = [
  { id: 'featured', name: 'Featured', icon: 'star', description: 'Most popular integrations' },
  { id: 'developer', name: 'Developer Tools', icon: 'code', description: 'Code, CI/CD, version control, monitoring' },
  { id: 'search', name: 'Search & Web', icon: 'search', description: 'Web search, browsing, scraping' },
  { id: 'database', name: 'Databases', icon: 'database', description: 'SQL, NoSQL, vector, serverless' },
  { id: 'communication', name: 'Communication', icon: 'message-square', description: 'Chat, email, messaging' },
  { id: 'cloud', name: 'Cloud & DevOps', icon: 'cloud', description: 'AWS, GCP, Vercel, Cloudflare, IaC' },
  { id: 'productivity', name: 'Productivity', icon: 'clipboard-list', description: 'Calendar, Drive, project mgmt' },
  { id: 'knowledge', name: 'Knowledge', icon: 'book-open', description: 'Memory, research, notes, wikis' },
  { id: 'ai', name: 'AI & Models', icon: 'cpu', description: 'Model hubs, image generation' },
  { id: 'sales', name: 'CRM & Prospection', icon: 'target', description: 'CRM, leads, outreach, pipeline de vente' },
  { id: 'marketing', name: 'Marketing', icon: 'megaphone', description: 'Email, réseaux sociaux, SEO, pub' },
  { id: 'support', name: 'Support Client', icon: 'headphones', description: 'Tickets, chat live, helpdesk' },
  { id: 'ecommerce', name: 'E-Commerce', icon: 'shopping-bag', description: 'Boutiques, commandes, stock, produits' },
  { id: 'hr', name: 'RH & Recrutement', icon: 'briefcase', description: 'Paie, recrutement, onboarding' },
  { id: 'finance', name: 'Finance', icon: 'credit-card', description: 'Compta, facturation, paiements' },
  { id: 'design', name: 'Design', icon: 'pen-tool', description: 'Figma, assets, UI tools' },
  { id: 'media', name: 'Media', icon: 'music', description: 'Music, video, streaming' },
  { id: 'security', name: 'Security', icon: 'shield', description: 'OSINT, monitoring, scanning' },
  { id: 'system', name: 'System', icon: 'terminal', description: 'Files, OS, shell access' },
  { id: 'reasoning', name: 'Reasoning', icon: 'brain', description: 'Thinking, planning, logic' },
  { id: 'utilities', name: 'Utilities', icon: 'wrench', description: 'Weather, time, automation' },
];
